# .readthedocs.yaml
version: 0.1.2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  # Option 1: Install via requirements.txt
  extra_requirements:
    - docs
sphinx:
  configuration: docs/source/conf.py
