version: 2

# Tell RTD to operate from inside docs/source/
subdirectory: docs/source

sphinx:
  configuration: conf.py

python:
  install:
    - method: pip
      path: ../../  # go back to project root to install your package

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Optional formats (safe to omit if only HTML is needed)
formats:
  - pdf
  - epub
