# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  # Install from pyproject.toml's "docs" extras
  install:
    - method: pip
      path: .
      extra_requirements: [docs]

sphinx:
  configuration: docs/source/conf.py