# .readthedocs.yaml
version: 0.1.2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/source/conf.py

# Optionally declare Python requirements for building docs
python:
  install:
    - requirements: docs/requirements.txt
