version: 2

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Optional output formats (remove if not needed)
formats:
  - pdf
  - epub